# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailBoxWebserver', '0002_auto_20170201_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='Nachricht_text',
            field=models.TextField(verbose_name='Nachrichtentext'),
        ),
        migrations.AlterField(
            model_name='nachricht',
            name='zeitstempel',
            field=models.DateTimeField(unique=True),
        ),
    ]
