# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailBoxWebserver', '0003_auto_20170201_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nachricht',
            name='zeitstempel',
            field=models.FloatField(),
        ),
    ]
